### ISSUE TITLE
crashes when launch 

### ISSUE THREAD

**Issue by master7720** [Pr3roxDLC/Catalyst#8]
[15:39:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:39:53] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:39:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:39:53] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[15:39:53] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_333, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_333
[15:39:53] [main/INFO] [FML]: Searching C:\Users\User\Desktop\MultiMC\instances\1.12.2\.minecraft\mods for mods
[15:39:53] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Catalyst-1.10.1.jar
[15:39:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:39:53] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:39:53] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_333]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.Runtime.exit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.System.exit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[15:39:53] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[15:39:53] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[15:39:53] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main"

**Comment by Pr3roxDLC** [comment]
Did you build from source or use the release?

**Comment by master7720** [comment]
> Did you build from source or use the release?

build from source

**Comment by Pr3roxDLC** [comment]
hm okay, can you try launching the game directly and not through multimc, seems like youre not the first person with this [kind of crash](https://github.com/SpongePowered/Mixin/issues/211) when using multimc

**Comment by Pr3roxDLC** [comment]
ah yes nvm i see the problem, please use the shadow jar, otherwise you will be missing certain classes

**Comment by master7720** [comment]
> ah yes nvm i see the problem, please use the shadow jar, otherwise you will be missing certain classes

ah ok thanks man

**Comment by master7720** [comment]
when i use the shadow jar the mod doesnt load

**Comment by therealbush** [comment]
> when i use the shadow jar the mod doesnt load

iq
